version: "0.2"
language: en
dictionaries:
  - css
  - html
  - typescript
enableFiletypes:
  - ignore
  - properties
  - svelte
  - xml
files:
  - "**/.*"
  - "**/*.{css,js,json,jsonc,html,md,scss,svelte,svg,yaml,yml,xml}"
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
  - data/**/*.json
  - dist/**
  - admin/**
  - .gitignore
words:
  - astros
  - camelcase
  - Cloudinary
  - danurbanowicz
  - Decap
  - DeepL
  - deepmerge
  - dompurify
  - Gitea
  - gzipped
  - hotlinking
  - iarna
  - IIFE
  - indexeddb
  - infobars
  - jsdoc
  - kyoshino
  - pexels
  - Photoshop
  - Pixabay
  - PKCE
  - plusplus
  - pnpm
  - postcss
  - prefs
  - previewable
  - privatemaker
  - proxify
  - proxyfied
  - Ragdoll
  - reimagined
  - Roadmap
  - safesearch
  - singleline
  - singtonic
  - smol
  - stylelint
  - Sveitia
  - sveltejs
  - Sveltia
  - templatized
  - Typecheck
  - unadded
  - uncategorized
  - unflatten
  - unlinkable
  - unproxify
  - Uploadcare
  - Vite
  - WCAG
  - weba
  - webformat
  - whitespaces
  - xslx
  - zanhk
overrides:
  - language: en-gb
    filename: "**/*.md"
